### ISSUE TITLE
Missing function to check if a query filter value exists

### ISSUE THREAD

**Issue by bloodhunterd** [Vection-Framework/Vection#1]
Currently there is no possiblity to get a query filter value without catching a type error exception, if the value does not exist.

`Return value of Vection\Component\MessageBus\Query\Helper\QueryFilter::getValue() must be of the type string, null returned`

A function like valueExists() would fix this issue.

**Comment by BKlemm** [comment]
Solved with 4e4f657cb20ab319ae8ccb7da0ad3124a7fd79dc

**Comment by bloodhunterd** [comment]
Now I'm getting a compile error, see...

`Declaration of Vection\Component\MessageBus\Query\Helper\QueryFilter::getValue(string $name): ?string must be compatible with Vection\Contracts\MessageBus\Query\Helper\QueryFilterInterface::getValue(string $name): string`

Please fix this as well ;-)

**Comment by BKlemm** [comment]
fixed!
